# Generated by Django 5.1.4 on 2025-02-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_remove_teacherprofile_office_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='subject',
            field=models.CharField(choices=[('Math', 'Math'), ('Science', 'Science'), ('English', 'English')], default='English', max_length=100),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='assigned_classes',
            field=models.CharField(default='Not Assigned', max_length=100),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='full_name',
            field=models.CharField(default='Unknown', max_length=150),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='phone_number',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='subject_specialization',
            field=models.CharField(default='Not Specified', max_length=100),
        ),
    ]
