# Generated by Django 5.1.4 on 2025-03-06 19:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_class_alter_timetable_class_name_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='class_name',
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='teachers',
        ),
        migrations.AlterField(
            model_name='timetable',
            name='subject',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
