# Generated by Django 5.1.4 on 2025-03-14 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_alter_timetable_class_name_remove_subject_teachers_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('day', 'time_slot', 'class_name')},
        ),
        migrations.AddField(
            model_name='timetable',
            name='time_slot',
            field=models.CharField(choices=[('7:30 - 8:30', '7:30 - 8:30'), ('8:30 - 9:30', '8:30 - 9:30'), ('9:30 - 10:30', '9:30 - 10:30'), ('11:00 - 11:50', '11:00 - 11:50'), ('11:50 - 12:40', '11:50 - 12:40'), ('12:40 - 1:30', '12:40 - 1:30'), ('2:30 - 3:30', '2:30 - 3:30'), ('3:30 - 4:30', '3:30 - 4:30'), ('4:30 - 5:30', '4:30 - 5:30')], default='7:30 - 8:30', max_length=20),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='time',
        ),
    ]
