# Generated by Django 5.1.4 on 2025-03-20 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_studentassignmentupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignmentupload',
            name='assignment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assignment.teacherassignment'),
            preserve_default=False,
        ),
    ]
