# Generated by Django 5.1.4 on 2025-03-20 16:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_studentassignmentupload_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignmentupload',
            name='uploaded_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
